import os   
from setuptools import setup

setup(
    name = "Beremiz",
    version = "1.1",
    author = "Edouard Tisserant",
    author_email = "edouard.tisserant@gmail.com",
    description = ("Open Source framework for automation."),
    license = "GNU GPL2",
    keywords = "automation beremiz iec61131 plcopen",
    url = "http://www.beremiz.org/",
    platforms=('Any'),
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Topic :: Utilities",
        "License :: OSI Approved :: BSD License",
    ],
)
#     packages=[
#         'docutil',
#         'editors',
#         'svgui/pyjs',
#         'svgui',
#         'targets/Generic',
#         'targets/Linux',
#         'targets/Win32',
#         'targets/Xenomai',
#         'targets',
#         'c_ext',
#         'canfestival',
#         'graphics',
#         'connectors/PYRO',
#         'connectors/WAMP',
#         'connectors',
#         'controls/DebugVariablePanel',
#         'controls',
#         'dialogs',
#         'util',
#         'wxglade_hmi',
#         'xmlclass',
#         'plcopen',
#         'py_ext',
#         'runtime'],